
is_simulation: true

control_mode: 0 #velocity mode

body_mass: 10
body_height: 0.28
body_inertia: [ 0.24, 0, 0, 0, 0.80, 0, 0, 0, 1.0 ]

hip_length: 0.08505
upper_length: 0.2
lower_length: 0.2

com_offset:
  velocity: [ 0.005, 0.00145, 0.000515 ] # vel mode
  position: [ -0.005, 0.0024, 0.000515 ] # pos mode
  walk: [ -0.005, 0.0012, 0.000515 ]     # walk mode

hip_offset: [ [ 0.1805, -0.047, 0. ],
              [ 0.1805, 0.047, 0. ],
              [ -0.1805, -0.047, 0. ],
              [ -0.1805, 0.047, 0. ] ]

default_hip_positions: [ [ 0.17, -0.135, 0 ],
                         [ 0.17, 0.135, 0 ],
                         [ -0.195, -0.135, 0 ],
                         [ -0.195, 0.135, 0 ] ]

abad_kp: 100.0
abad_kd: 1.0
hip_kp: 100.0
hip_kd: 2.0
knee_kp: 100.0
knee_kd: 2.0
