speed_update_mode: 0 # const twist
const_twist:
  linear: [0.2, 0., 0.]
  angular: 0. # 0.2

controllerList: ["joint_state_controller", "FL_hip_controller", "FL_thigh_controller",
                 "FL_calf_controller", "FR_hip_controller", "FR_thigh_controller",
                 "FR_calf_controller", "RL_hip_controller", "RL_thigh_controller",
                 "RL_calf_controller", "RR_hip_controller", "RR_thigh_controller",
                 "RR_calf_controller"]
