name: aliengo
stance_leg_params:
    force_dim: 3
    KP:  [100., 100., 100., 300., 300., 200.] # robot_com_position, robot_com_roll_pitch_yaw
    KD:  [40., 30., 10., 20., 20., 30.] # robot_com_velocity, robot_com_roll_pitch_yaw_rate
    max_ddq: [10., 10., 10., 20., 20., 20.]
    min_ddq: [-10., -10., -10., -20., -20., -20.]
    acc_weight: [1., 1., 1., 10., 10., 1.]